#Based on https://github.com/alpercitak/svelte-docker
version: '3'
services:
  app-node:
    image: jgme/jgme-io
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 127.0.0.1:3002:3000